# Generated by Django 3.1.4 on 2021-04-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='fantasy_universe',
            field=models.CharField(default='Example: D&D', max_length=100),
        ),
    ]
