# Generated by Django 3.1.4 on 2021-04-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='ability_type',
            field=models.CharField(blank=True, choices=[('Spell', 'Spell'), ('Feature', 'Feature')], max_length=100),
        ),
    ]
