# Generated by Django 3.1.4 on 2021-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_auto_20210418_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='name',
            field=models.JSONField(),
        ),
    ]
