# Generated by Django 3.1.4 on 2021-04-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0005_auto_20210418_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='name',
            field=models.JSONField(default=[]),
        ),
    ]
