# Generated by Django 3.1.4 on 2021-04-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0007_auto_20210418_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='spell',
            name='class_type',
        ),
        migrations.AddField(
            model_name='spell',
            name='class_type',
            field=models.ManyToManyField(to='spells.ClassType'),
        ),
    ]
